Repository microsoft/Qcodes, pull requests merged in 2019-01, with the labels that each got.

#1437 Avoid warnings in CI, and a bit more
  qcodes/data/hdf5_format.py
  qcodes/instrument/parameter.py
  qcodes/monitor/monitor.py
  qcodes/plots/qcmatplotlib.py
  qcodes/tests/common.py
  qcodes/tests/dataset/test_database_creation_and_upgrading.py
  qcodes/tests/dataset/test_database_extract_runs.py
  qcodes/tests/dataset/test_datasaver.py
  qcodes/tests/dataset/test_dataset_basic.py
  qcodes/tests/dataset/test_metadata.py
  qcodes/tests/dataset/test_sqlite_base.py
  qcodes/tests/dataset/test_sqlite_connection.py
  qcodes/tests/test_parameter.py
  qcodes/tests/test_wrong_address.py
Labels: bug

#1445 Ensure that partial run creation is completly rolled back
  qcodes/dataset/sqlite_base.py
  qcodes/tests/dataset/test_sqlite_base.py
Labels: bug, new dataset

#1367 Hashable and Immutable ParamSpec
  qcodes/dataset/param_spec.py
  qcodes/tests/dataset/test_paramspec.py
Labels: enhancement
