Repository microsoft/Qcodes, pull requests merged in 2020-11, with the labels that each got.

#2384 Add complety types to R & S and Ithaco drivers
  qcodes/instrument_drivers/ithaco/Ithaco_1211.py
  qcodes/instrument_drivers/rohde_schwarz/RTO1000.py
  qcodes/instrument_drivers/rohde_schwarz/SGS100A.py
  qcodes/instrument_drivers/rohde_schwarz/ZNB.py
  qcodes/instrument_drivers/rohde_schwarz/private/HMC804x.py
  setup.cfg
Labels: automerge

#2386 Type most tektronix drivers
  qcodes/instrument/parameter.py
  qcodes/instrument_drivers/tektronix/AWG5208.py
  qcodes/instrument_drivers/tektronix/AWG70000A.py
  qcodes/instrument_drivers/tektronix/AWG70002A.py
  qcodes/instrument_drivers/tektronix/AWGFileParser.py
  qcodes/instrument_drivers/tektronix/DPO7200xx.py
  qcodes/instrument_drivers/tektronix/Keithley_2000.py
  qcodes/instrument_drivers/tektronix/Keithley_2400.py
  qcodes/instrument_drivers/tektronix/Keithley_2450.py
  qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
  qcodes/instrument_drivers/tektronix/Keithley_3706A.py
  qcodes/instrument_drivers/tektronix/Keithley_6500.py
  qcodes/instrument_drivers/tektronix/Keithley_s46.py
  qcodes/instrument_drivers/tektronix/TPS2012.py
  qcodes/instrument_drivers/tektronix/keithley_7510.py
  setup.cfg
Labels: automerge, driver

#2394 remove nose config from setup.cfg
  setup.cfg
Labels: automerge

#2395 Mark Keysight sd common module as deprecated
  qcodes/instrument_drivers/Keysight/SD_common/__init__.py
Labels: automerge

#2393 Type awg5014c driver
  qcodes/instrument_drivers/tektronix/AWG5014.py
  setup.cfg
Labels: automerge, driver

#2397 Reverse logic for which modules are typed
  qcodes/__init__.py
  setup.cfg
Labels: automerge

#2408 Qcodes notebook update for Ithaco
  docs/examples/driver_examples/Qcodes example with Ithaco.ipynb
  docs/examples/files/ithaco_setup.png
Labels: automerge

#2418 Add support h5py 3 to legacy dataset
  qcodes/data/hdf5_format.py
  requirements.txt
Labels: automerge

#2423 Remove deprecated inappropriate names
  qcodes/instrument_drivers/Keysight/keysightb1500/message_builder.py
  qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
Labels: automerge

#2429 upgrade versioneer to 0.19
  qcodes/__init__.py
  qcodes/_version.py
  versioneer.py
Labels: automerge

#2341 Add full type checking of Qdac drivers
  qcodes/instrument_drivers/QDev/QDac_channels.py
  qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
  setup.cfg
Labels: driver

#2422 Remove deprecated add_result, get_setpoints, add_results_to_queue methods of DataSet
  docs/examples/DataSet/Benchmarking.ipynb
  docs/examples/DataSet/Pedestrian example of subscribing to a DataSet.ipynb
  docs/examples/DataSet/subscriber json exporter.ipynb
  qcodes/dataset/data_set.py
Labels: automerge

#2434 Add default terminator for Agilent E8527D
  qcodes/instrument_drivers/agilent/E8527D.py
Labels: automerge, bug

#2007 Added fixed frequency readout mode (CW mode) to ZNB driver
  qcodes/instrument_drivers/rohde_schwarz/ZNB.py
Labels: driver

#2396 Add types to Alazar drivers
  qcodes/instrument_drivers/AlazarTech/ATS.py
  qcodes/instrument_drivers/AlazarTech/ATS_acquisition_controllers.py
  qcodes/instrument_drivers/AlazarTech/dll_wrapper.py
  qcodes/instrument_drivers/AlazarTech/utils.py
  qcodes/tests/drivers/AlazarTech/test_alazar_buffer.py
  setup.cfg
Labels: automerge

#2444 Removed logging.info message from spyder part of helpers.py
  qcodes/utils/helpers.py
Labels: automerge, backport needed

#2446 Add PycQED to related projects
  docs/community/related_projects.rst
Labels: automerge, docs

#2451 updated zenodo for v0.20.1
  README.rst
Labels: automerge

#2450 Start replacing implicit use of Any with explicit
  qcodes/configuration/config.py
  qcodes/dataset/descriptions/versioning/serialization.py
  qcodes/dataset/json_exporter.py
  qcodes/dataset/measurements.py
  qcodes/instrument_drivers/Keysight/keysight_34980a.py
  qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/commandhandler.py
  qcodes/interactive_widget.py
  qcodes/tests/dataset/test_subscribing.py
  qcodes/tests/drivers/test_lakeshore.py
  qcodes/tests/parameter/test_snapshot.py
  qcodes/utils/dataset/doNd.py
  qcodes/utils/deprecate.py
  qcodes/utils/helpers.py
  qcodes/utils/metadata.py
  qcodes/utils/validators.py
Labels: automerge

#2452 Add RST and OPC dialogues, display_enable for Keysight_34465A pyvisa sim
  qcodes/instrument/sims/Keysight_34465A.yaml
  qcodes/tests/drivers/test_keysight_34465a.py
Labels: automerge

#2454 No implicit any generics outside drivers and tests
  qcodes/configuration/config.py
  qcodes/data/data_set.py
  qcodes/station.py
  setup.cfg
Labels: automerge

#2456 Minor typing improvements
  qcodes/dataset/sqlite/queries.py
  qcodes/instrument/base.py
Labels: automerge

#2457 No implicit generic in tests
  qcodes/tests/common.py
  qcodes/tests/helpers/test_json_encoder.py
  qcodes/tests/helpers/test_strip_attrs.py
  qcodes/tests/instrument_mocks.py
  qcodes/tests/test_autoloadable_channels.py
  setup.cfg
Labels: automerge

#2462 fix setup.py importlib metadata version
  setup.py
Labels: automerge

#2463 Remove implicit generic Any from some of the instrument drivers
  qcodes/instrument_drivers/Keysight/Infiniium.py
  qcodes/instrument_drivers/Keysight/N52xx.py
  qcodes/instrument_drivers/Keysight/keysight_e4980a.py
  qcodes/instrument_drivers/QDev/QDac_channels.py
  qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
  qcodes/instrument_drivers/rigol/DG1062.py
  qcodes/instrument_drivers/stahl/stahl.py
  qcodes/instrument_drivers/stanford_research/SR86x.py
  qcodes/instrument_drivers/tektronix/Keithley_s46.py
Labels: automerge

#2475 Add complete types to Validators
  qcodes/instrument/channel.py
  qcodes/instrument/function.py
  qcodes/instrument/parameter.py
  qcodes/instrument_drivers/tektronix/AWG70000A.py
  qcodes/tests/parameter/conftest.py
  qcodes/tests/validators/test_basic.py
  qcodes/utils/types.py
  qcodes/utils/validators.py
  setup.cfg
Labels: automerge

#2480 refactor logic to find scale and prefix into public function
  qcodes/dataset/plotting.py
  qcodes/tests/dataset/test_plotting.py
  qcodes/utils/plotting.py
Labels: automerge
