Repository microsoft/Qcodes, pull requests merged in 2020-12, with the labels that each got.

#2492 Fix parameter name in ats9870: EXTERNAL_CLOCK_10MHz_REF
  docs/examples/writing_drivers/Creating-Instrument-Drivers.ipynb
  qcodes/instrument_drivers/AlazarTech/ATS9870.py
Labels: automerge

#2488 plotting: don't scale empty units
  qcodes/tests/dataset/test_plotting.py
  qcodes/utils/plotting.py
Labels: automerge

#2493 Keysight 34465A: Add missing parameters to pyvisa sim yaml file
  qcodes/instrument/sims/Keysight_34465A.yaml
Labels: automerge, driver

#2510 Use the latest json schema draft supported by python jsonschema validator
  qcodes/configuration/qcodesrc_schema.json
  setup.py
Labels: automerge

#2525 sync importlib metadata requirement
  docs_requirements.txt
  requirements.txt
  science_requirements.txt
  test_requirements.txt
Labels: dependencies

#2526 Add kwarg for experiment id to doNd functions (With tests)
  qcodes/dataset/experiment_container.py
  qcodes/dataset/measurements.py
  qcodes/tests/dataset/test_doNd.py
  qcodes/utils/dataset/doNd.py
Labels: automerge

#2532 Keysight B1500: ensure making snapshot of the pyvisa-sim instrument does not raise warnings
  qcodes/instrument/sims/keysight_b1500.yaml
  qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1500.py
Labels: automerge, driver

#2531 Add impedance autorange parameter to Keysight E4980A driver
  qcodes/instrument_drivers/Keysight/keysight_e4980a.py
Labels: driver

#2479 Changelog for qcodes 0.21.0 (Unreleased)
  docs/changes/0.21.0.rst
  docs/changes/index.rst
Labels: docs

#2544 Remove deprecated SD_common module
  qcodes/instrument_drivers/Keysight/SD_common/SD_AWG.py
  qcodes/instrument_drivers/Keysight/SD_common/SD_DIG.py
  qcodes/instrument_drivers/Keysight/SD_common/SD_Module.py
  qcodes/instrument_drivers/Keysight/SD_common/__init__.py
  qcodes/tests/drivers/test_Keysight_M3201A.py
  setup.cfg
Labels: automerge
