Repository microsoft/Qcodes, pull requests merged in 2021-02, with the labels that each got.

#2679 Bump numpy dependency to 1.20 and fix remaining typing issues
  docs_requirements.txt
  qcodes/instrument_drivers/Keysight/N9030B.py
  requirements.txt
  test_requirements.txt
Labels: dependencies

#2686 fix #2105 by expanding 1 elem arrays when loading
  qcodes/dataset/sqlite/queries.py
  qcodes/tests/dataset/test_data_set_cache.py
Labels: automerge

#2690 automatic validator for agilent E8527D based on options
  qcodes/instrument_drivers/agilent/E8527D.py
Labels: automerge

#2694 add license to sdist
  MANIFEST.in
Labels: automerge

#2722 Add two more SMUs to B1500 yaml sim file
  qcodes/instrument/sims/keysight_b1500.yaml
Labels: driver

#2746 bump pylint, astroid and lazy-object-proxy
  science_requirements.txt
Labels: dependencies

#2613 Add drivers for Keysight PXIE devices, M960X and M9336A
  qcodes/instrument_drivers/Keysight/KtM960x.py
  qcodes/instrument_drivers/Keysight/KtM960xDefs.py
  qcodes/instrument_drivers/Keysight/KtMAwg.py
  qcodes/instrument_drivers/Keysight/KtMAwgDefs.py
Labels: driver
