Repository microsoft/Qcodes, pull requests merged in 2021-01, with the labels that each got.

#2581 Add explicit test of dataset length
  qcodes/tests/dataset/test_dataset_basic.py
Labels: automerge

#2585 awg70000 add test of warning when waveform is clipped
  qcodes/tests/drivers/test_tektronix_AWG70000A.py
Labels: automerge

#2569 Add tests with minimal requirements
  .github/workflows/pytest-min-versions.yaml
  qcodes/instrument/visa.py
  setup.py
Labels: automerge

#2560 Build docs with Sphinx 3.4.1
  docs_requirements.txt
  qcodes/instrument/channel.py
  science_requirements.txt
Labels: automerge, dependencies

#2512 Updating doNd notebook with comparing Measurement context manager with qcodes doNd
  docs/examples/DataSet/Performing-measurements-using-qcodes-parameters-and-dataset.ipynb
  docs/examples/DataSet/Using_doNd_functions_in_comparison_to_Measurement_context_manager_for_performing_measurements.ipynb
  docs/examples/DataSet/Using_the_doNd_functions_for_running_experiments.ipynb
Labels: docs

#2561 Add checks for signal current level and voltage level queries in Keysight E4980A driver
  qcodes/instrument/sims/Keysight_E4980A.yaml
  qcodes/instrument_drivers/Keysight/keysight_e4980a.py
  qcodes/tests/drivers/test_keysight_e4980a.py
Labels: automerge

#2611 bump importlib-metadata to 3.4.0
  docs_requirements.txt
  requirements.txt
  science_requirements.txt
  test_requirements.txt
Labels: dependencies

#2616 add doNd kwarg to measure parameters in thread pool
  qcodes/utils/dataset/doNd.py
  qcodes/utils/threading.py
  setup.cfg
Labels: automerge

#2647 Add support for Mypy 0.800
  qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
  qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
  qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/commandhandler.py
  qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/server.py
  qcodes/instrument_drivers/rigol/DS4000.py
  test_requirements.txt
Labels: automerge, dependencies

#2655 Allow passing ParamSpecBase to DataSet's "get data" methods
  qcodes/dataset/data_set.py
Labels: automerge

#2507 feature: add native xarray support and concatenation of DataFrames/DataArrays
  docs/examples/15_minutes_to_QCoDeS.ipynb
  docs/examples/DataSet/Accessing-data-in-DataSet.ipynb
  docs/examples/DataSet/Working-With-Pandas-and-XArray.ipynb
  environment.yml
  qcodes/dataset/data_set.py
  qcodes/dataset/data_set_cache.py
  qcodes/tests/dataset/conftest.py
  qcodes/tests/dataset/test_dataset_basic.py
  requirements.txt
  setup.py
Labels: automerge

#2648 Add bias volt param to Basel SP983C
  docs/examples/driver_examples/Qcodes example with Basel SP983c Preamp.ipynb
  qcodes/instrument_drivers/basel/sp983c.py
Labels: automerge, driver

#2649 Keysight B1500: support measuring any number of channels during IV sweep
  docs/examples/driver_examples/Qcodes example with Keysight B1500 Parameter Analyzer.ipynb
  qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_base.py
  qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
Labels: automerge, driver

#2664 ravel data before inserting into cache
  qcodes/dataset/measurements.py
  qcodes/dataset/sqlite/queries.py
  qcodes/tests/dataset/test_data_set_cache.py
  qcodes/tests/dataset/test_doNd.py
Labels: automerge

#2654 Refactor data merging when loading from disk
  qcodes/dataset/data_set.py
  qcodes/dataset/data_set_cache.py
  qcodes/dataset/sqlite/queries.py
Labels: automerge

#2666 Additional tests for cache loading bug fixed in #2664
  qcodes/tests/dataset/test_data_set_cache.py
Labels: automerge

#2668 Update Zenodo link for qcodes v0.22.0
  README.rst
Labels: automerge

#2675 Add missing entries to v0.22.0 changelog
  docs/changes/0.22.0.rst
Labels: automerge, backport needed

#2674 Remove left over usage of deprecated get_data_as_pandas_dataframe
  docs/examples/15_minutes_to_QCoDeS.ipynb
  docs/examples/DataSet/DataSet-class-walkthrough.ipynb
  docs/examples/DataSet/Performing-measurements-using-qcodes-parameters-and-dataset.ipynb
  docs/examples/DataSet/Working-With-Pandas-and-XArray.ipynb
  docs/examples/driver_examples/Qcodes example with Ithaco.ipynb
  qcodes/dataset/data_set.py
  qcodes/dataset/data_set_cache.py
  qcodes/tests/dataset/test_dataset_basic.py
Labels: automerge, backport needed
